import Head from "next/head";
import Layout from "../layouts/Layout";
import { motion } from "framer-motion";
import { useContext } from "react";
import { StateContext } from "../store/state-context";

export default function Home() {
  const ctx = useContext(StateContext);
  // variant for about title
  const variants = {
    normal: {
      opacity: 0,
    },
    before: {
      y: 80,
      x: -20,
      opacity: 0,
    },
    after: {
      y: 0,
      x: 0,
      opacity: 1,
    },
  };
  return (
    <div>
      <Head>
        <title>Programming League</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout bg="bg2">
        <div className="grid w-full grid-cols-2 gap-4">
          <div>
            {/*  eslint-disable-next-line @next/next/no-img-element */}
            {/*about motion div */}
            <motion.div
              initial="before"
              animate="after"
              variants={variants}
              transition={{ duration: 0.5 }}
            >
              <img src="/images/image 3.png" alt="3" />
              <div className="relative my-10">
                <h1 className="tracking-[0.4em] font-surrend text-[#FCEF41] z-10 absolute -top-[5px] -left-[5px]">
                  ABOUT US
                </h1>
                <h1 className="tracking-[0.4em] font-surrend text-[#FF00F5] absolute -top-[2px] -left-[2px]">
                  ABOUT US
                </h1>
                <h1 className="tracking-[0.4em] font-surrend text-[#00C2FF]">
                  ABOUT US
                </h1>
              </div>
            </motion.div>
            <motion.div
              variants={variants}
              initial="normal"
              animate="after"
              transition={{ duration: 1 }}
            >
              <p className="mb-10 text-2xl font-medium tracking-widest text-justify md:text-3xl">
                Programming League National is an annual competitive programming
                contest organised by the Faculty of Computer Science and
                Information Technology, University of Malaya where teams of 3
                compete to solve algorithmic problems.
              </p>
              <p className="mb-10 text-2xl font-medium tracking-widest text-justify md:text-3xl">
                For the past few years, it had been a university-wide
                competition. In 2021, we are ramping it up by assembling
                students from all universities across Malaysia to compete among
                the best in the field!
              </p>
              <p className="mb-10 text-2xl font-medium tracking-widest text-justify md:text-3xl">
                We aim to host the most colossal, eminent and pioneering
                programming contest of all time and ultimately, uphold Malaysia
                programming standards.
              </p>
            </motion.div>
          </div>
          <motion.div
            variants={variants}
            initial="normal"
            animate="after"
            transition={{ duration: 0.5 }}
            className="flex items-center"
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src="/images/PLN-Glitch 1.gif"
              alt="logo"
              className="object-contain w-full h-[600px]"
            />
          </motion.div>
        </div>
      </Layout>
    </div>
  );
}
