import Head from "next/head";
import TopLayout from "../layouts/TopLayout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Programming League</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopLayout bg="bg3">
        <div className="relative pt-10">
          {/*  eslint-disable-next-line @next/next/no-img-element */}
          <img src="/images/image 3.png" alt="3" />
          <div className="relative my-10">
            <h1 className="tracking-[0.4em] font-surrend text-[#FCEF41] z-10 absolute -top-[5px] -left-[5px]">
              ANNOUNCEMENTS
            </h1>
            <h1 className="tracking-[0.4em] font-surrend text-[#FF00F5] absolute -top-[2px] -left-[2px]">
              ANNOUNCEMENTS
            </h1>
            <h1 className="tracking-[0.4em] font-surrend text-[#00C2FF]">
              ANNOUNCEMENTS
            </h1>
          </div>
        </div>
        <div className="grid w-full gap-4 lg:grid-cols-2">
          <div className="max-h-[55vh] lg:max-h-[75vh] space-y-10 overflow-y-scroll">
            {Array(10)
              .fill()
              .map((_, i) => (
                <div key={i} className="grid grid-cols-4 gap-10">
                  <div className="col-span-3">
                    <div className="text-lg text-justify border_box">
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Atque dicta quaerat repellat mollitia id culpa optio
                      voluptatibus tenetur pariatur eum!
                    </div>
                  </div>
                  <div className="flex items-center justify-center">
                    <div className="relative">
                      <p className="p-4 text-xl border-b-4 border-t-4 border-[#00C2FF] tracking-wider gradient_text">
                        {i + 1 <= 9 ? `0${i + 1}` : i + 1}
                      </p>
                      <div className="absolute -top-2 -right-0 w-5 h-1 bg-[#00C2FF]"></div>
                    </div>
                  </div>
                </div>
              ))}
          </div>
          <div className="hidden lg:block">
            <div className="flex items-center h-full">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src="/images/faq 2.gif"
                alt="logo"
                className="object-contain w-full max-h-[500px]"
              />
            </div>
          </div>
        </div>
      </TopLayout>
    </div>
  );
}
