import Head from "next/head";
import Layout from "../layouts/Layout";
import { motion } from "framer-motion";
import { useContext } from "react/cjs/react.development";
import { StateContext } from "../store/state-context";

const logo_variant = {
  hidden: {
    opacity: 0,
    scale: 1.5,
  },
  show: {
    opacity: 1,
    scale: 1,
  },
};
const local_variant = {
  hidden: {
    scale: 0.5,
    opacity: 0.0,
  },
  show: {
    scale: 1,
    opacity: 1,
    transition: {
      duration: 0.5,
    },
  },
};

const variant = {
  normal: {
    opacity: 0,
  },
  aboutus: {
    top: "calc(100vh - 90vh)",
    opacity: 0.3,
  },
  overview: {
    left: "calc(100vw - 60%)",
    opacity: 0.3,
  },
  results: {
    left: "calc(70vw - 60%)",
    opacity: 0.3,
  },
  after: {
    y: 0,
    top: "auto",
    left: "auto",
    opacity: 1,
  },
};

export default function Home() {
  const ctx = useContext(StateContext);

  let animationType = "normal";
  if (ctx.preState === "overview") {
    animationType = "overview";
  } else if (ctx.preState === "aboutus") {
    animationType = "aboutus";
  } else if (ctx.preState === "results") {
    animationType = "results";
  } else {
    animationType = "normal";
  }
  return (
    <div>
      <Head>
        <title>Programming League</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout bg="bg3">
        <motion.div
          className="relative pt-10"
          initial={animationType}
          variants={variant}
          animate="after"
          transition={{ duration: 0.5, ease: "easeOut" }}
        >
          {/*  eslint-disable-next-line @next/next/no-img-element */}
          <img src="/images/image 3.png" alt="3" />
          <div className="relative my-10">
            <h1 className="tracking-[0.4em] font-surrend text-[#FCEF41] z-10 absolute -top-[5px] -left-[5px]">
              FAQ
            </h1>
            <h1 className="tracking-[0.4em] font-surrend text-[#FF00F5] absolute -top-[2px] -left-[2px]">
              FAQ
            </h1>
            <h1 className="tracking-[0.4em] font-surrend text-[#00C2FF]">
              FAQ
            </h1>
          </div>
        </motion.div>
        <div className="grid w-full gap-4 lg:grid-cols-2">
          <div className="max-h-[65vh] lg:max-h-[75vh] space-y-10 overflow-y-scroll overflow-x-hidden scrollbar">
            {Array(10)
              .fill()
              .map((_, i) => (
                <motion.div
                  viewport={{ once: true }}
                  initial="hidden"
                  whileInView="show"
                  variants={local_variant}
                  key={i}
                  className="grid grid-cols-4 gap-10"
                >
                  <div className="col-span-3">
                    <div className="text-lg text-justify border_box">
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Atque dicta quaerat repellat mollitia id culpa optio
                      voluptatibus tenetur pariatur eum!
                    </div>
                  </div>
                  <div className="flex items-center justify-center">
                    <div className="relative">
                      <p className="p-4 text-xl border-b-4 border-t-4 border-[#00C2FF] tracking-wider gradient_text">
                        {i + 1 <= 9 ? `0${i + 1}` : i + 1}
                      </p>
                      <div className="absolute -top-2 -right-0 w-5 h-1 bg-[#00C2FF]"></div>
                    </div>
                  </div>
                </motion.div>
              ))}
          </div>
          <div className="hidden lg:block">
            <motion.div
              className="flex items-center h-full"
              variants={logo_variant}
              transition={{
                duration: 1,
              }}
              initial="hidden"
              animate="show"
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src="/images/faq 1.gif"
                alt="logo"
                className="object-contain w-full max-h-[500px]"
              />
            </motion.div>
          </div>
        </div>
      </Layout>
    </div>
  );
}
