import { motion } from "framer-motion";
import Head from "next/head";
import Layout from "../layouts/Layout";

export default function Home() {
  const variant = {
    before:{
      opacity:0
    },
    after:{
      opacity:1
    }
  }
  return (
    <div>
      <Head>
        <title>Programming League</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout bg="bg1">
        <div className="grid w-full grid-cols-2 gap-4">
          <motion.div variants={variant} initial="before" animate="after" transition={{duration:1}}>
            <div>
              <div className="relative mb-4">
                <h6 className="text-4xl md:text-[40px] tracking-widest font-extralight text-[white] z-10 absolute -top-[3px] -left-[3px]">
                  UNIVERSITI MALAYA
                </h6>
                <h6 className="text-4xl md:text-[40px] tracking-widest font-extralight text-[#FF00F5] absolute -top-[1px] -left-[1px]">
                  UNIVERSITI MALAYA
                </h6>
                <h6 className="text-4xl md:text-[40px] tracking-widest font-extralight text-[#00C2FF]">
                  UNIVERSITI MALAYA
                </h6>
              </div>
            </div>
            <div className="mb-10 space-y-3">
              <div className="relative">
                <h1 className="tracking-wider font-surrend text-[#FCEF41] z-10 absolute -top-[5px] -left-[5px]">
                  PROGRAMMING
                </h1>
                <h1 className="tracking-wider font-surrend text-[#FF00F5] absolute -top-[2px] -left-[2px]">
                  PROGRAMMING
                </h1>
                <h1 className="tracking-wider font-surrend text-[#00C2FF]">
                  PROGRAMMING
                </h1>
              </div>
              <div className="flex items-center justify-between">
                <div className="relative">
                  <h1 className="tracking-wider font-surrend text-[#FCEF41] z-10 absolute -top-[5px] -left-[5px]">
                    LEAGUE
                  </h1>
                  <h1 className="tracking-wider font-surrend text-[#FF00F5] absolute -top-[2px] -left-[2px]">
                    LEAGUE
                  </h1>
                  <h1 className="tracking-wider font-surrend text-[#00C2FF]">
                    LEAGUE
                  </h1>
                </div>
                <div className="relative">
                  <h1 className="tracking-wider font-surrend text-[#FCEF41] z-10 absolute -top-[5px] -left-[5px]">
                    20
                  </h1>
                  <h1 className="tracking-wider font-surrend text-[#FF00F5] absolute -top-[2px] -left-[2px]">
                    20
                  </h1>
                  <h1 className="tracking-wider font-surrend text-[#00C2FF]">
                    20
                  </h1>
                </div>
              </div>
              <div className="flex items-center justify-between">
                <div className="relative">
                  <h1 className="tracking-wider font-surrend text-[#FCEF41] z-10 absolute -top-[5px] -left-[5px]">
                    NATIONAL
                  </h1>
                  <h1 className="tracking-wider font-surrend text-[#FF00F5] absolute -top-[2px] -left-[2px]">
                    NATIONAL
                  </h1>
                  <h1 className="tracking-wider font-surrend text-[#00C2FF]">
                    NATIONAL
                  </h1>
                </div>
                <div className="relative">
                  <h1 className="tracking-wider font-surrend text-[#FCEF41] z-10 absolute -top-[5px] -left-[5px]">
                    22
                  </h1>
                  <h1 className="tracking-wider font-surrend text-[#FF00F5] absolute -top-[2px] -left-[2px]">
                    22
                  </h1>
                  <h1 className="tracking-wider font-surrend text-[#00C2FF]">
                    22
                  </h1>
                </div>
              </div>
            </div>
            <div className="flex items-center justify-end w-full">
              <div className="relative">
                <div className="absolute -top-[3px] left-0 bg-[#FCEF41] btn_1 z-10 px-11 py-2 cursor-pointer">
                  <h3 className="font-bold text-black">LETS GO!</h3>
                </div>
                <div className="absolute -top-2 -left-1 bg-[#FF00F5] btn_1 px-11 py-2 cursor-pointer">
                  <h3 className="font-bold text-black">LETS GO!</h3>
                </div>
                <div className="bg-[#00C2FF] px-11 py-2 btn_1 cursor-pointer">
                  <h3 className="font-bold text-black">LETS GO!</h3>
                </div>
              </div>
            </div>
          </motion.div>
          <motion.div className="flex items-center" variants={variant} initial="before" animate="after" transition={{duration:1}}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src="/images/PLN-Glitch 1.gif"
              alt="logo"
              className="object-contain w-full h-[400px]"
            />
          </motion.div>
        </div>
      </Layout>
    </div>
  );
}
