import Head from "next/head";
import Layout from "../layouts/Layout";
import { motion } from "framer-motion";
import { useContext } from "react";
import { StateContext } from "../store/state-context";

const variant = {
  normal: {
    opacity: 0.0,
  },
  aboutus: {
    top: "calc(100vh - 97%)",
    left: "-100%",
    opacity: 0.3,
  },
  faq: {
    left: "-100%",
    opacity: 0.3,
  },
  results: {
    opacity: 0.3,
    left: "calc(20vw - 100%)",
  },
  after: {
    top: "auto",
    left: "auto",
    opacity: 1.0,
  },
  aboutusImg: {
    left: "calc(73vw - 60%)",
    opacity: 0.8,
  },
};

export default function Home() {
  const ctx = useContext(StateContext);

  let imageType = "normal";
  if (ctx.preState == "aboutus") {
    imageType = "aboutusImg";
  }

  let animationType = "normal";
  if (ctx.preState === "aboutus") {
    animationType = "aboutus";
  } else if (ctx.preState === "faq") {
    animationType = "faq";
  } else if (ctx.preState === "results") {
    animationType = "results";
  } else {
    animationType = "normal";
  }
  return (
    <div>
      <Head>
        <title>Programming League</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout bg="bg2_gif">
        <div className="grid w-full h-full gap-4 lg:grid-cols-2">
          <motion.div
            className="relative flex items-center"
            variants={variant}
            initial={imageType}
            animate="after"
            transition={{ duration: 0.5, ease: "easeOut" }}
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src="/images/PLN-Glitch 1.gif"
              alt="logo"
              className="object-contain w-full hidden lg:block h-[600px]"
            />
          </motion.div>
          <motion.div
            variants={variant}
            initial={animationType}
            animate="after"
            transition={{ duration: 0.5 }}
            className="relative pt-10"
          >
            {/*  eslint-disable-next-line @next/next/no-img-element */}
            <img src="/images/image 3.png" alt="3" />
            <div className="relative my-10">
              <h1 className="tracking-[0.4em] font-surrend text-[#FCEF41] z-10 absolute -top-[5px] -left-[5px]">
                OVERVIEW
              </h1>
              <h1 className="tracking-[0.4em] font-surrend text-[#FF00F5] absolute -top-[2px] -left-[2px]">
                OVERVIEW
              </h1>
              <h1 className="tracking-[0.4em] font-surrend text-[#00C2FF]">
                OVERVIEW
              </h1>
            </div>
            <p className="mb-10 font-medium tracking-widest text-justify h-80">
              Lorem, ipsum.
            </p>
          </motion.div>
        </div>
      </Layout>
    </div>
  );
}
