/* eslint-disable @next/next/no-sync-scripts */
import Head from "next/head";
import Layout from "../layouts/Layout";
import { motion } from "framer-motion";
import {
  VerticalTimeline,
  VerticalTimelineElement,
} from "react-vertical-timeline-component";
import "react-vertical-timeline-component/style.min.css";

const variant = {
  normal: {
    opacity: 0.0,
  },
  down:{
    y:-300,
    opacity:0.0
  },
  after: {
    top: "auto",
    left: "auto",
    opacity: 1.0,
    y:0
  },
};

export default function Home() {
  let animationType = "normal";

  return (
    <div>
      <Head>
        <title>Programming League National 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/PLN-Glitch 1.png" />
      </Head>
      <Layout bg="bg2_gif">
        <div className="w-full h-full">
          <div>
            <div className="flex justify-center my-10">
              <motion.div className="relative" 
                variants={variant}
                initial="down"
                animate="after"
                transition={{ duration: 0.5 }}>
                {/*  eslint-disable-next-line @next/next/no-img-element */}
                <img
                  className="absolute -top-10"
                  src="/images/image 3.png"
                  alt="3"
                />
                <h1 className="tracking-[0.4em] font-surrend text-[#FCEF41] z-10 absolute -top-[5px] -left-[5px]">
                  OVERVIEW
                </h1>
                <h1 className="tracking-[0.4em] font-surrend text-[#FF00F5] absolute -top-[2px] -left-[2px]">
                  OVERVIEW
                </h1>
                <h1 className="tracking-[0.4em] font-surrend text-[#00C2FF]">
                  OVERVIEW
                </h1>
              </motion.div>
            </div>
            <div className="min-h-[70vh] w-full">
              <VerticalTimeline>
                <VerticalTimelineElement
                  className="vertical-timeline-element--work"
                  contentStyle={{
                    background: "#003366",
                    color: "#fff",
                  }}
                  contentArrowStyle={{
                    borderRight: "7px solid  #003366",
                  }}
                  date="21st February 2022"
                  iconStyle={{ background: "#003366", color: "#fff" }}
                  // icon={<WorkIcon />}
                >
                  <h3 className="vertical-timeline-element-title md:text-2xl text-xl">
                    Registration Opens
                  </h3>
                  {/* <h4 className="vertical-timeline-element-subtitle">
                    Miami, FL
                  </h4>
                  <p>
                    Creative Direction, User Experience, Visual Design, Project
                    Management, Team Leading
                  </p> */}
                </VerticalTimelineElement>
                <VerticalTimelineElement
                  className="vertical-timeline-element--work"
                  contentStyle={{
                    background: "#003366",
                    color: "#fff",
                  }}
                  contentArrowStyle={{
                    borderRight: "7px solid  #003366",
                  }}
                  date="5th March 2022 9.00 a.m. to 12.30 p.m."
                  iconStyle={{ background: "#003366", color: "#fff" }}
                  // icon={<WorkIcon />}
                >
                  <h3 className="vertical-timeline-element-title md:text-2xl text-xl">
                    Competitive Programming Workshop
                  </h3>
                </VerticalTimelineElement>
                <VerticalTimelineElement
                  className="vertical-timeline-element--work"
                  contentStyle={{
                    background: "#003366",
                    color: "#fff",
                  }}
                  contentArrowStyle={{
                    borderRight: "7px solid  #003366",
                  }}
                  date="13rd March 2022"
                  iconStyle={{ background: "#003366", color: "#fff" }}
                  // icon={<WorkIcon />}
                >
                  <h3 className="vertical-timeline-element-title md:text-2xl text-xl">
                    Registration Closes
                  </h3>
                </VerticalTimelineElement>
                <VerticalTimelineElement
                  className="vertical-timeline-element--work"
                  contentStyle={{
                    background: "#003366",
                    color: "#fff",
                  }}
                  contentArrowStyle={{
                    borderRight: "7px solid  #003366",
                  }}
                  date="19th March 2022 8.30 a.m. to 12.30 p.m."
                  iconStyle={{ background: "#003366", color: "#fff" }}
                  // icon={<WorkIcon />}
                >
                  <h3 className="vertical-timeline-element-title md:text-2xl text-xl">
                    Preliminary Round
                  </h3>
                </VerticalTimelineElement>
                <VerticalTimelineElement
                  className="vertical-timeline-element--work"
                 contentStyle={{
                    background: "#003366",
                    color: "#fff",
                  }}
                  contentArrowStyle={{
                    borderRight: "7px solid  #003366",
                  }}
                  date="2nd April 2022 8.00 a.m. to 4.30 p.m."
                  iconStyle={{ background: "#003366", color: "#fff" }}
                  // icon={<WorkIcon />}
                >
                  <h3 className="vertical-timeline-element-title md:text-2xl text-xl">
                    Final Round
                  </h3>
                </VerticalTimelineElement>
              </VerticalTimeline>
            </div>
          </div>
        </div>
      </Layout>
    </div>
  );
}
